# Adapted from https://packaging.python.org/en/latest/appveyor/

branches:
  only:
  - master

environment:
  matrix:
    # only run 2 tests, these take 3 minutes each
    # We skip Python 3.5, as the AppVeyor run fails with something related to
    # (an old) pip being confused about something and failing.
    # - PYTHON: "C:\\Python35"
      # TOX_ENV: "py35"
    - PYTHON: "C:\\Python36-x64"
      TOX_ENV: "py36"
    - PYTHON: "C:\\Python37-x64"
      TOX_ENV: "py37"

install:
  - git submodule update --init --recursive
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -vv -e %TOX_ENV%"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_status_changed: true
    on_build_failure: true
    on_build_success: false
