language: python
python:
    - "2.7_with_system_site_packages"
    - "3.3"
sudo: false
addons:
    apt:
        packages:
            - python-numpy
            - python-scipy
            - python-matplotlib
            - python-tk
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
    - pip install coveralls sympy
    - python setup.py install
script:
    - nosetests --with-doctest --with-coverage --cover-package=pymola --where=pymola
after_success:
    - coveralls
