language: python
python:
    - "2.7"
    - "3.2"
sudo: false
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
cache:
  - ccache
  - pip
install:
  - pip install coveralls coverage
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_wait pip install -r requirements-py2.txt ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_wait pip install -r requirements-py3.txt ; fi
  - python setup.py install
script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  #- coverage run setup.py test
#after_success:
  #- coveralls
