language: python
python:
    - "2.7_with_system_site_packages"
    - "3.3"
    - "3.4"
sudo: false
#addons:
    #apt:
        #packages:
            #- python-opencv
            #- python-scipy
            #- python-scipy
install:
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    - pip install coveralls
    - python setup.py install
script:
    - nosetests --with-doctest --with-coverage --cover-package=pymola --where=pymola
after_success:
    - coveralls
