sudo: false
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - ./create_conda_env.sh testing
  - source activate pymola
  - python setup.py install

script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - coverage run setup.py test
after_success:
  - coveralls
