language: python
python:
  - "2.7"
# install required system libraries
# before_install:
#  - sudo apt-get update --fix-missing -qq

# command to install dependencies from source
# note, separating requirements so that travis
# will get output in less than 5 min and won't
# terminate, using q to keep build info to a
# minumum for dependencies
install:
  - pip install -q coverage coveralls nose antlr4-python2-runtime jinja2 sympy

# command to run tests
script: coverage run setup.py test
after_success:
  - coveralls
