language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
# install required system libraries
before_install:
  - sudo apt-get update --fix-missing -qq
  - sudo apt-get install python-scipy python-numpy
install:
  - pip install coverage coveralls nose antlr4-python2-runtime jinja2 sympy

# command to run tests
script: coverage run setup.py test
after_success:
  - coveralls
